### ISSUE TITLE
Сервер

### ISSUE THREAD

**Issue by Noveller** [talyosha/terminal-app#1]
Привет, в readme вы написали что необходимо предоставить ip, port и т.д. для сервера. Не совсем понимаю о чем идёт речь.

**Comment by talyosha** [comment]
> Привет, в readme вы написали что необходимо предоставить ip, port и т.д. для сервера. Не совсем понимаю о чем идёт речь.

Здравствуйте! После того как открывается терминал , нас спрашывают в консоли вышеперечисленыие даныие для того что-бы приложения смогла конектится к серверу и отправлять ему команды .

**Comment by talyosha** [comment]
> Привет, в readme вы написали что необходимо предоставить ip, port и т.д. для сервера. Не совсем понимаю о чем идёт речь.

Предоставляю даныие одного тестого сервера для проверки: 
IP: 138.197.180.206
Port: 22
Username: normal-bash-user
Password: qazwsxedc

Но можно подключится к любому серверу !

**Comment by Noveller** [comment]
> > Привет, в readme вы написали что необходимо предоставить ip, port и т.д. для сервера. Не совсем понимаю о чем идёт речь.
> 
> Здравствуйте! После того как открывается терминал , нас спрашывают в консоли вышеперечисленыие даныие для того что-бы приложения смогла конектится к серверу и отправлять ему команды .

Хорошо, о каких ip, port идёт речь? Я так понимаю нужно запустить сервер который будет слушать этот порт. Не так ли?

**Comment by Noveller** [comment]
Пожалуйста, предоставьте, при открытии приложения,  возможность использования терминалом.
модуль ssh2 это конечно здорово, но относительно задачи в целом это overengineering.
Спасибо за понимание.

**Comment by talyosha** [comment]
> > > Привет, в readme вы написали что необходимо предоставить ip, port и т.д. для сервера. Не совсем понимаю о чем идёт речь.
> > 
> > 
> > Здравствуйте! После того как открывается терминал , нас спрашывают в консоли вышеперечисленыие даныие для того что-бы приложения смогла конектится к серверу и отправлять ему команды .
> 
> Хорошо, о каких ip, port идёт речь? Я так понимаю нужно запустить сервер который будет слушать этот порт. Не так ли?

Нет , это не так . Для того чтобы выполнять команды на любом сервере нам нужно подключится к нему через SSH - соеденения . Ип - это ип сервера к которуму мы подключаемся  , порт - это SSH порт , по дефолту это 22 , но может использоватся и другои . username - это название учётныи записи пользователя допущеного к управлению системой , password это пароль данои учётныи запись. 
Все эмуляторы терминала нуждаются в этих даных (
https://ru.wikipedia.org/wiki/%D0%AD%D0%BC%D1%83%D0%BB%D1%8F%D1%82%D0%BE%D1%80_%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%D0%B0)

Не нужно слушать никакой порт. После npm start , в браузере откроется окно , и там будет спрашивать вначале ип сервера - напишите 138.197.180.206 ( это один мой тестовый сервер , но вы можете подключатся к любому серверу с SSH соединениям ) , потом port - напишите 22, username: normal-bash-user, password: qazwsxedc
После некоторых секунд вам предоставится возможность для выполнения команд

**Comment by talyosha** [comment]
> Пожалуйста, предоставьте, при открытии приложения, возможность использования терминалом.
> модуль ssh2 это конечно здорово, но относительно задачи в целом это overengineering.
> Спасибо за понимание.
Задача " Создайте эмулятор терминала в браузере с помощью React.  "
Эмулятор терминала - нуждается всегда в этих даных . ( https://ru.wikipedia.org/wiki/%D0%AD%D0%BC%D1%83%D0%BB%D1%8F%D1%82%D0%BE%D1%80_%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%D0%B0 )

Может в имеете в в вид под "Эмулятор терминала" -  Интерфейс командной строки  (https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81_%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9_%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8) ?

Если это так то , пожалуиста уточните ешё раз и я сделаю как вы скажете !
Вам огромное спасибо за понимание !
